/**
 * Bootstrap + game loop + the capture/inspection harness.
 * OWNER: core.
 *
 * Feature agents: do not edit this file. Register your module in core/modules.js
 * (already done) and implement your own file.
 */
import * as THREE from 'three';
import { Engine } from './core/engine.js';
import { Input } from './core/input.js';
import { MANIFEST } from './core/modules.js';
import { U, WORLD, setCausticOccluders } from './core/globals.js';
import { SHOTS, applyShot } from './core/shots.js';
import { makeRNG } from './core/rng.js';

const params = new URLSearchParams(location.search);
const engine = new Engine(document.getElementById('app'));
const input = new Input(engine.canvas);

const modules = new Map();
const status = [];

const ctx = {
  engine,
  renderer: engine.renderer,
  scene: engine.scene,
  camera: engine.camera,
  U, WORLD, input,
  rng: makeRNG(Number(params.get('seed') ?? 1337)),
  uiRoot: document.getElementById('ui'),
  params,
  time: { t: 0, dt: 0, frame: 0, timeOfDay: Number(params.get('tod') ?? 0.42) },

  /**
   * WHICH HARNESS IS DRIVING, stated explicitly.
   *
   * survival.js inferred "we are in a screenshot battery, so do not let the
   * player die" from `?capture=1` — a flag that only ever meant "render
   * deterministically". tools/play.mjs also sends capture=1, so EVERY play route
   * ran with a 35 HP god-mode floor and the game could not kill you. The defect
   * "health freezes at exactly 35" was that floor, and it survived several rounds
   * because the harness itself was changing the thing it was measuring.
   *
   *   harness.still  a static shot battery — nobody is playing, freezing vitals is reasonable
   *   harness.play   a scripted playthrough — this is REAL GAMEPLAY, change nothing
   *   harness.none   a human at the keyboard
   *
   * Gameplay may branch on `harness.still`. It must NEVER branch on `capture`.
   * Anything a module suppresses must be reported through godModes below.
   */
  harness: Object.freeze({
    mode: params.get('harness') || (params.has('capture') ? 'still' : 'none'),
    get still() { return this.mode === 'still'; },
    get play() { return this.mode === 'play'; },
    get none() { return this.mode === 'none'; },
  }),

  /**
   * Any module that suppresses or overrides normal behaviour for the harness MUST
   * register it here, so a critic can see at a glance that what they are measuring
   * is not the real game.
   */
  godModes: [],
  declareGodMode: (id, what) => {
    const s = `${id}: ${what}`;
    if (!ctx.godModes.includes(s)) ctx.godModes.push(s);
  },
  get: (id) => modules.get(id),
  has: (id) => modules.has(id),
  /** Modules announce optional capabilities other modules may use. */
  provide: (k, v) => { ctx[k] = v; },
};

const bootbar = document.getElementById('bootbar');
const setBoot = (p) => { if (bootbar) bootbar.style.width = `${Math.round(p * 100)}%`; };

async function loadModules() {
  const list = [...MANIFEST].sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
  let done = 0;
  for (const entry of list) {
    const t0 = performance.now();
    const rec = { id: entry.id, ok: false, error: null, initMs: 0, missing: false };
    try {
      const mod = (await entry.path()).default;
      if (!mod) throw new Error('no default export');
      mod.id = mod.id || entry.id;
      if (mod.init) await mod.init(ctx);
      modules.set(mod.id, mod);
      rec.ok = true;
      rec.stub = !!mod.stub;
    } catch (err) {
      const msg = String(err && err.message || err);
      rec.missing = /Failed to fetch dynamically imported|Cannot find module|resolve/i.test(msg);
      rec.error = msg;
      if (!rec.missing) console.error(`[module:${entry.id}]`, err);
    }
    rec.initMs = +(performance.now() - t0).toFixed(1);
    status.push(rec);
    setBoot(++done / list.length);
  }
}

// ---------------------------------------------------------------- loop
const MAX_DT = 1 / 20;
let last = performance.now();
let running = true;
let fpsAcc = 0, fpsN = 0, fps = 0, fpsTimer = 0;

const _occl = [];
/** Ablation: ?nocaustocc=1 removes every caustic occluder so the term can be
 *  measured against a build that has none. Declared in godModes when set. */
const NO_CAUSTIC_OCCL = new URLSearchParams(location.search).get('nocaustocc') === '1';
if (NO_CAUSTIC_OCCL) ctx.declareGodMode('core', 'caustic occluders disabled (?nocaustocc=1)');
function simulate(dt) {
  ctx.time.dt = dt;
  ctx.time.t += dt;
  ctx.time.frame++;
  U.uTime.value = ctx.time.t;

  for (const m of modules.values()) {
    if (!m.update) continue;
    try { m.update(dt, ctx.time.t, ctx); }
    catch (err) {
      console.error(`[update:${m.id}]`, err);
      m.update = null; // disable a crashing module rather than kill the frame
      const s = status.find((x) => x.id === m.id);
      if (s) { s.ok = false; s.error = 'update: ' + err.message; }
    }
  }
  U.uCamPos.value.copy(engine.camera.position);
  U.uSfPixelScale.value = engine.canvas.clientHeight
    / (2 * Math.tan(engine.camera.fov * Math.PI / 360));

  /**
   * Publish the caustic occluders for this frame.
   *
   * The diver is the one occluder that is always present and is exactly what
   * the reference shallows-floor plate shows breaking the caustic field. Life
   * and vehicle modules can add their own through setCausticOccluders(); core
   * seeds the list with the player so the term is never dead.
   */
  const _mv = ctx.get('movement');
  const _pp = _mv?.position;
  _occl.length = 0;
  if (_pp && !NO_CAUSTIC_OCCL) _occl.push({ pos: _pp, radius: 1.1 });
  for (const m of modules.values()) {
    if (!m.causticOccluders) continue;
    try {
      const extra = m.causticOccluders(ctx);
      if (extra) for (const o of extra) { if (_occl.length < 8) _occl.push(o); }
    } catch { m.causticOccluders = null; }
  }
  setCausticOccluders(_occl);
  updateFallbacks();
  for (const m of modules.values()) {
    if (!m.preRender) continue;
    try { m.preRender(ctx); } catch (err) { console.error(`[preRender:${m.id}]`, err); m.preRender = null; }
  }
  input.endFrame();
}

function frame(now) {
  requestAnimationFrame(frame);
  if (!running) return;
  // Clamp low as well as high: a zero dt divides to NaN, and browsers do deliver
  // duplicate timestamps (tab restore, first frame after a stall).
  const dt = Math.min(MAX_DT, Math.max(1 / 1000, (now - last) / 1000));
  last = now;
  simulate(dt);
  engine.render();

  fpsAcc += dt; fpsN++; fpsTimer += dt;
  if (fpsTimer > 0.5) { fps = fpsN / fpsAcc; fpsAcc = 0; fpsN = 0; fpsTimer = 0; }
}

// ---------------------------------------------------------------- harness
const CN = {
  THREE, engine, ctx, modules, U, WORLD, SHOTS,
  ready: false,
  status: () => ({
    ready: CN.ready,
    // When the loop is frozen (captures, play routes) the rAF counter is stale,
    // so fall back to the measured cost of the manual steps.
    fps: +(running ? fps : (CN._fpsAcc || CN.stepFps || 0)).toFixed(1),
    fpsSource: running ? 'raf' : 'step',
    stepMs: +(CN.stepMs || 0).toFixed(2),
    drawCalls: engine.drawCalls,
    triangles: engine.triangles,
    camera: engine.camera.position.toArray().map((v) => +v.toFixed(2)),
    depth: +Math.max(0, -engine.camera.position.y).toFixed(1),
    modules: status,
    // Shader link failures are REAL failures. They used to be invisible here —
    // modules init fine, then silently draw nothing — so a broken build was
    // indistinguishable from an art problem for a whole round.
    failed: [
      ...status.filter((s) => !s.ok && !s.missing).map((s) => `${s.id}: ${s.error}`),
      ...engine.shaderErrors,
    ],
    shaderErrors: engine.shaderErrors,
    harness: ctx.harness.mode,
    // Non-empty means what you are measuring is NOT the real game.
    godModes: ctx.godModes,
    brokenBuild: engine.shaderErrors.length > 0,
    missing: status.filter((s) => s.missing).map((s) => s.id),
    stubs: status.filter((s) => s.stub).map((s) => s.id),
    errors: CN.errors.slice(0, 20),
  }),
  errors: [],
  /** Pause rAF so captures are deterministic. */
  freeze(v = true) { running = !v; return !running; },
  /**
   * Advance the simulation by n fixed steps (default 1/60s).
   *
   * Measures its own wall-clock cost. The rAF loop's fps counter is gated on
   * `running`, so while a capture holds the loop frozen and drives step() by
   * hand — which is exactly what tools/play.mjs does — that counter stays 0 and
   * every performance figure a play route reported was meaningless.
   */
  step(n = 1, dt = 1 / 60) {
    const t0 = performance.now();
    for (let i = 0; i < n; i++) simulate(dt);
    engine.render();
    const ms = performance.now() - t0;
    CN.stepMs = ms;
    CN.stepFps = ms > 0 ? 1000 / (ms / Math.max(1, n)) : 0;
    // Rolling average so a single hitch does not dominate a route's report.
    CN._fpsAcc = (CN._fpsAcc || 0) * 0.9 + CN.stepFps * 0.1;
  },
  stepMs: 0,
  stepFps: 0,
  /** Settle: run n steps so LOD/streaming/animation reach steady state. */
  settle(seconds = 2) { CN.step(Math.round(seconds * 60), 1 / 60); },
  setCamera({ pos, look, yaw, pitch, fov }) {
    const c = engine.camera;
    if (pos) c.position.fromArray(pos);
    if (fov) { c.fov = fov; c.updateProjectionMatrix(); }
    if (look) c.lookAt(new THREE.Vector3().fromArray(look));
    else if (yaw !== undefined || pitch !== undefined) {
      c.rotation.set(0, 0, 0, 'YXZ');
      c.rotation.y = (yaw ?? 0) * Math.PI / 180;
      c.rotation.x = (pitch ?? 0) * Math.PI / 180;
    }
    c.updateMatrixWorld(true);
    U.uCamPos.value.copy(c.position);
  },
  listShots: () => Object.keys(SHOTS),
  async shot(name) { return applyShot(name, ctx, CN); },
  setTimeOfDay(t) { ctx.time.timeOfDay = t; },
};
window.__CN = CN;

addEventListener('error', (e) => CN.errors.push(String(e.message)));
addEventListener('unhandledrejection', (e) => CN.errors.push('promise: ' + String(e.reason)));

/**
 * Fallback lighting + background.
 *
 * Scene lighting belongs to render/sky.js and the medium to render/underwater.js,
 * but every module has to be judgeable on its own while its neighbours are still
 * stubs — and with no light at all, terrain renders as a flat silhouette and a
 * critic ends up reviewing the absence of a sun. So: if nobody supplied a light
 * or a background by the end of boot, core installs a reasonable one driven by
 * the same shared uniforms sky.js writes. Whoever owns sky simply adds their own
 * lights and these never appear.
 */
/**
 * Shadows are opt-in per-mesh in three.js, and an independent critic measured the
 * cost of leaving them off: a stone sitting on sand read luminance 119 against
 * sand at 112-125 — statistically invisible, because occlusion, not albedo, is
 * most of the signal in a real seabed photograph. Rather than rely on 17 agents
 * each remembering two flags, core turns shadows on for everything by default.
 * A module that genuinely needs an exception sets `mesh.userData.noShadow = true`.
 */
function enableShadows(root) {
  root.traverse((o) => {
    if (!o.isMesh && !o.isInstancedMesh && !o.isSkinnedMesh) return;
    if (o.userData.noShadow) return;
    o.castShadow = true;
    o.receiveShadow = true;
  });
}

function installFallbacks() {
  let hasLight = false, hasSun = false;
  engine.scene.traverse((o) => {
    if (o.isLight) hasLight = true;
    if (o.isDirectionalLight) hasSun = true;
  });

  if (!hasSun) {
    const sun = new THREE.DirectionalLight(U.uSunColor.value.clone(), U.uSunIntensity.value);
    sun.position.copy(U.uSunDir.value).multiplyScalar(400);
    sun.castShadow = true;
    sun.shadow.mapSize.set(2048, 2048);
    sun.shadow.camera.near = 1; sun.shadow.camera.far = 900;
    const d = 160;
    Object.assign(sun.shadow.camera, { left: -d, right: d, top: d, bottom: -d });
    sun.shadow.bias = -0.0006;
    sun.name = '__fallbackSun';
    engine.scene.add(sun);
    engine.scene.add(sun.target);
    CN.fallbackSun = sun;
  }
  if (!hasLight) {
    const hemi = new THREE.HemisphereLight(
      U.uAmbientTop.value.clone(), U.uAmbientBottom.value.clone(), 1.15);
    hemi.name = '__fallbackHemi';
    engine.scene.add(hemi);
    CN.fallbackHemi = hemi;
  }
  if (!engine.scene.background && !engine.scene.environment) {
    // Underwater there is no "sky" — the background IS the medium's in-scattered
    // colour, so distant geometry converges into it instead of into black.
    engine.scene.background = new THREE.Color();
    CN.fallbackBackground = true;
  }
}

/** Keep the fallback rig following whatever the shared uniforms currently say. */
function updateFallbacks() {
  const sun = CN.fallbackSun;
  if (sun) {
    sun.position.copy(U.uSunDir.value).multiplyScalar(400).add(engine.camera.position);
    sun.target.position.copy(engine.camera.position);
    sun.target.updateMatrixWorld();
    sun.color.copy(U.uSunColor.value);
    sun.intensity = U.uSunIntensity.value * THREE.MathUtils.lerp(0.12, 1, U.uDepthDarken.value);
  }
  if (CN.fallbackHemi) {
    CN.fallbackHemi.color.copy(U.uAmbientTop.value);
    CN.fallbackHemi.groundColor.copy(U.uAmbientBottom.value);
  }
  if (CN.fallbackBackground && engine.scene.background?.isColor) {
    // Must match uwInscatter's HORIZONTAL far-field limit exactly, which is
    // mix(fog, scatter, strength) — not raw fog. When it was raw fog, infinitely
    // distant water and infinitely distant geometry resolved to different colours
    // and the horizon showed a hard step (measured: 103 -> 74 over ~3% of frame
    // height in open water, where there is no geometry to explain it).
    engine.scene.background
      .copy(U.uFogColor.value)
      .lerp(U.uScatterColor.value, U.uScatterStrength.value);
  }
}

(async function boot() {
  await loadModules();
  installFallbacks();
  enableShadows(engine.scene);
  // Modules stream geometry in later (terrain chunks, flora, creatures), so keep
  // applying it as the scene grows rather than only once at boot.
  CN.enableShadows = enableShadows;
  setInterval(() => enableShadows(engine.scene), 1000);
  // warm shader compilation so the first captured frame is not a black/stall frame
  try { await engine.renderer.compileAsync(engine.scene, engine.camera); } catch { /* older three */ }
  simulate(1 / 60);
  engine.render();
  CN.ready = true;
  document.getElementById('boot')?.classList.add('hide');
  // Seed `last` on one frame and start the loop on the NEXT, otherwise the first
  // frame is delivered with dt === 0 (last and now are the same timestamp) and
  // any module that divides by dt produces NaN on frame one. Two agents hit this.
  requestAnimationFrame((t) => { last = t; requestAnimationFrame(frame); });
})();
